// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ─── WEB ────────────────────────────────────────────────────────────────────
  // ATENÇÃO: Você precisa registrar um app web no Firebase Console:
  //   1. Acesse console.firebase.google.com → seu projeto → "Adicionar app" → Web
  //   2. Copie o valor de "appId" (formato: 1:688654083193:web:XXXXXXXXXXXXXXXX)
  //   3. Cole abaixo no campo appId e salve o arquivo.
  // Os demais valores já estão corretos para o projeto app-de-van-5f05d.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3EZNhBkJM1NiIqf35z55IWQ7ie1vG7sM',
    appId: '1:688654083193:web:07e305605b5e95ecade0a8',
    messagingSenderId: '688654083193',
    projectId: 'app-de-van-5f05d',
    authDomain: 'app-de-van-5f05d.firebaseapp.com',
    storageBucket: 'app-de-van-5f05d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3EZNhBkJM1NiIqf35z55IWQ7ie1vG7sM',
    appId: '1:688654083193:android:ee6d2c056025c909ade0a8',
    messagingSenderId: '688654083193',
    projectId: 'app-de-van-5f05d',
    storageBucket: 'app-de-van-5f05d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxrJCmfCXqpIXwqEfRD1PSaUfB2nLKzH8',
    appId: '1:688654083193:ios:62921e79299bfe9dade0a8',
    messagingSenderId: '688654083193',
    projectId: 'app-de-van-5f05d',
    storageBucket: 'app-de-van-5f05d.firebasestorage.app',
    iosBundleId: 'com.example.piVan',
  );
}
